// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/captured_note.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1407255643202042497),
    name: 'CapturedNote',
    lastPropertyId: const obx_int.IdUid(6, 9123639503545899433),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1101611934885520711),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9031447168788706071),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4804992250534136546),
        name: 'imageBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8554364282912279380),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 73526378004897827),
        name: 'course',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9123639503545899433),
        name: 'textContent',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 1407255643202042497),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CapturedNote: obx_int.EntityDefinition<CapturedNote>(
      model: _entities[0],
      toOneRelations: (CapturedNote object) => [],
      toManyRelations: (CapturedNote object) => {},
      getId: (CapturedNote object) => object.id,
      setId: (CapturedNote object, int id) {
        object.id = id;
      },
      objectToFB: (CapturedNote object, fb.Builder fbb) {
        final imageBytesOffset = object.imageBytes == null
            ? null
            : fbb.writeListInt8(object.imageBytes!);
        final titleOffset = fbb.writeString(object.title);
        final courseOffset = fbb.writeString(object.course);
        final textContentOffset = object.textContent == null
            ? null
            : fbb.writeString(object.textContent!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(2, imageBytesOffset);
        fbb.addOffset(3, titleOffset);
        fbb.addOffset(4, courseOffset);
        fbb.addOffset(5, textContentOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final courseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final imageBytesParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGetNullable(buffer, rootOffset, 8)
                as Uint8List?;
        final textContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = CapturedNote(
          id: idParam,
          createdAt: createdAtParam,
          title: titleParam,
          course: courseParam,
          imageBytes: imageBytesParam,
          textContent: textContentParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CapturedNote] entity fields to define ObjectBox queries.
class CapturedNote_ {
  /// See [CapturedNote.id].
  static final id = obx.QueryIntegerProperty<CapturedNote>(
    _entities[0].properties[0],
  );

  /// See [CapturedNote.createdAt].
  static final createdAt = obx.QueryDateProperty<CapturedNote>(
    _entities[0].properties[1],
  );

  /// See [CapturedNote.imageBytes].
  static final imageBytes = obx.QueryByteVectorProperty<CapturedNote>(
    _entities[0].properties[2],
  );

  /// See [CapturedNote.title].
  static final title = obx.QueryStringProperty<CapturedNote>(
    _entities[0].properties[3],
  );

  /// See [CapturedNote.course].
  static final course = obx.QueryStringProperty<CapturedNote>(
    _entities[0].properties[4],
  );

  /// See [CapturedNote.textContent].
  static final textContent = obx.QueryStringProperty<CapturedNote>(
    _entities[0].properties[5],
  );
}
